export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';
export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS';
export const SET_BOOKMARKS_LOADING = 'SET_BOOKMARKS_LOADING';
export const SET_BOOKMARKS_ERROR = 'SET_BOOKMARKS_ERROR';