import {
  QueryConstraint,
  addDoc,
  collection,
  doc,
  getDoc,
  getDocs,
  limit,
  orderBy,
  query,
  startAfter,
  updateDoc,
  where,
} from 'firebase/firestore';
import { getDownloadURL, ref, uploadBytes } from 'firebase/storage';
import { FIREBASE_DB, FIREBASE_STORAGE } from '../../FirebaseConfig';
import convertFirestoreRecipeToAppRecipe from '../../utils/convertFirestoreRecipeToAppRecipe';
import { Recipe } from '../model/recipeModel';

export async function addRecipeToFirestore(
  recipeData: Recipe,
  userId: string
): Promise<string> {
  try {
    const docRef = await addDoc(collection(FIREBASE_DB, 'recipes'), {
      ...recipeData,
      userId, // Store the user ID with the recipe
      createdAt: new Date(), // Set the current date as the creation date
      updatedAt: new Date(), // Set the current date as the updated date
    });
    console.log('Recipe added to Firestore');
    return docRef.id; // Return the generated recipe ID
  } catch (error) {
    console.error('Error adding recipe to Firestore:', error);
    throw error;
  }
}

export async function getAllRecipes(
  lastFetchedRecipeId: string | null,
  limitNumber: number,
  userId?: string
) {
  // Create an array for query constraints
  let queryConstraints: Array<QueryConstraint> = [
    orderBy('updatedAt', 'desc'),
    limit(limitNumber),
  ];

  // Filter by userId if provided
  if (userId) {
    queryConstraints.push(where('userId', '==', userId));
  }

  // Modify the query if lastFetchedRecipeId exists
  if (lastFetchedRecipeId) {
    const lastSnapshot = await getDoc(
      doc(FIREBASE_DB, 'recipes', lastFetchedRecipeId)
    );
    queryConstraints.push(startAfter(lastSnapshot));
  }

  // Construct the final query using the query constraints
  const finalQuery = query(
    collection(FIREBASE_DB, 'recipes'),
    ...queryConstraints
  );

  // Execute the query and process the results

  const querySnapshot = await getDocs(finalQuery);
  const fetchedRecipes = querySnapshot.docs.map(
    convertFirestoreRecipeToAppRecipe
  );

  // Determine the new 'lastFetchedRecipeId' for pagination
  const newLastFetchedRecipeId =
    querySnapshot.docs.length === limitNumber
      ? querySnapshot.docs[querySnapshot.docs.length - 1].id
      : null;
  console.log('Recipes fetched:', fetchedRecipes);
  return {
    recipes: fetchedRecipes,
    lastFetchedRecipeId: newLastFetchedRecipeId,
  };
}

// Get recipe by id from Firestore database
export async function getRecipeById(recipeId: string) {
  try {
    const docRef = doc(FIREBASE_DB, 'recipes', recipeId);
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
      // Convert Firestore document to RecipeWithId type
      return convertFirestoreRecipeToAppRecipe(docSnap);
    } else {
      console.log('No such document!');
      return null;
    }
  } catch (error) {
    console.error('Error fetching document:', error);
    throw error;
  }
}

// Add image with an autogenerated id to Firestore database
export const addImage = async (imageData: { imageUrl: string }) => {
  try {
    await addDoc(collection(FIREBASE_DB, 'images'), imageData);
    console.log('Image added to Firestore');
  } catch (error) {
    console.error('Error adding image to Firestore:', error);
    throw error;
  }
};

// Get image by id from Firestore database
export async function getImageById(imageId: string) {
  try {
    const docRef = doc(FIREBASE_DB, 'images', imageId);
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
      return docSnap.data(); // Returns the document data
    } else {
      console.log('No such document!');
      return null;
    }
  } catch (error) {
    console.error('Error fetching document:', error);
    throw error;
  }
}

// Upload recipe image to Firestore
// export default function uploadImageToFirestore(
//   localFilePath: string,
//   recipeId: string
// ) {
//   return new Promise(async (resolve, reject) => {
//     try {
//       // Create a storage reference with the recipe ID
//       const storageRef = ref(FIREBASE_STORAGE, `recipes/${recipeId}.jpg`);

//       // Convert the local file path to a Blob or File object
//       const response = await fetch(localFilePath);
//       const blob = await response.blob();

//       // Upload the file to Firebase Storage
//       await uploadBytes(storageRef, blob);

//       // Get the download URL
//       const downloadURL = await getDownloadURL(storageRef);

//       // Save the download URL to Firestore
//       const recipeRef = doc(FIREBASE_DB, 'recipes', recipeId);
//       await setDoc(recipeRef, { imageUrl: downloadURL }, { merge: true });

//       resolve(downloadURL);
//     } catch (error) {
//       console.error('Error uploading image:', error);
//       reject(error);
//     }
//   });
// }

export async function uploadImageToFirestore(
  localFilePath: string,
  recipeId: string
): Promise<string | null> {
  try {
    const storageRef = ref(FIREBASE_STORAGE, `recipes/${recipeId}.jpg`);
    const response = await fetch(localFilePath);
    const blob = await response.blob();
    await uploadBytes(storageRef, blob);
    const downloadURL = await getDownloadURL(storageRef);
    await updateDoc(doc(FIREBASE_DB, 'recipes', recipeId), {
      imageUrl: downloadURL,
    });
    return downloadURL;
  } catch (error) {
    console.error('Error uploading image:', error);
    return null; // Return null in case of error
  }
}
